### ISSUE TITLE
A value that can be either a primitive or a record

### ISSUE THREAD

**Issue by scott-fleischman** [Gabriel439/Haskell-Dhall-JSON-Library#2]
Is it possible to create a Dhall file that will generate the following `stack.yaml`?

Each item in `packages` could either be a primitive value (string) or a record.

```
packages:
- '.'
- location:
    git: git@github.com:Gabriel439/Haskell-Dhall-Library.git
    commit: aeb7d165251a0612538e0ca8f84d60b5aaac6c8d
  subdirs: []
  extra-dep: true
```

Or written this way, the problem shifts to `location`, which is either a primitive value or a record.

```
packages:
- location: '.'
- location:
    git: git@github.com:Gabriel439/Haskell-Dhall-Library.git
    commit: aeb7d165251a0612538e0ca8f84d60b5aaac6c8d
  subdirs: []
  extra-dep: true
```

My tendency is to reach for Dhall's union type, but that is not a currently supported translation:

```
Explanation: Only primitive values, records, ❰List❱s, and ❰Optional❱ values can be translated from Dhall to JSON
```

It might be helpful to allow for unions to translate to overlapping types for situations like this.

Using unions in this way is more similar to TypeScript's union type, since the explicit tag would get lost in translation.
